server {
    listen 443 ssl;
    server_name web.demo.trustcloud.test web-app;

    ssl_certificate /etc/nginx/tls/web-app.crt;
    ssl_certificate_key /etc/nginx/tls/web-app.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
