// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboard() {
  return window['go']['tray']['GUIApp']['GetDashboard']();
}

export function FlashWindowAttention() {
  return window['go']['tray']['GUIApp']['FlashWindowAttention']();
}

export function HideWindow() {
  return window['go']['tray']['GUIApp']['HideWindow']();
}

export function ShowWindow() {
  return window['go']['tray']['GUIApp']['ShowWindow']();
}

export function StartEnrollmentInteractive() {
  return window['go']['tray']['GUIApp']['StartEnrollmentInteractive']();
}

export function StartUserLoginInteractive() {
  return window['go']['tray']['GUIApp']['StartUserLoginInteractive']();
}

export function LogoutUserSession() {
  return window['go']['tray']['GUIApp']['LogoutUserSession']();
}
