// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessEvents() {
  return window['go']['tray']['GUIApp']['GetAccessEvents']();
}

export function GetActiveSessions() {
  return window['go']['tray']['GUIApp']['GetActiveSessions']();
}

export function GetCatalogResources() {
  return window['go']['tray']['GUIApp']['GetCatalogResources']();
}

export function GetDashboard() {
  return window['go']['tray']['GUIApp']['GetDashboard']();
}

export function HideWindow() {
  return window['go']['tray']['GUIApp']['HideWindow']();
}

export function ShowWindow() {
  return window['go']['tray']['GUIApp']['ShowWindow']();
}
