// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';

export function GetDashboard():Promise<ipc.AgentDashboard>;

export function HideWindow():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartEnrollmentInteractive():Promise<ipc.StartEnrollmentInteractiveResponse>;

export function StartUserLoginInteractive():Promise<ipc.StartUserLoginInteractiveResponse>;

export function LogoutUserSession():Promise<ipc.LogoutUserSessionResponse>;
