// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';
import {tray} from '../models';

export function GetAccessEvents():Promise<ipc.AccessEventsResponse>;

export function GetActiveSessions():Promise<ipc.ActiveSessionsResponse>;

export function GetCatalogResources():Promise<ipc.CatalogResourcesResponse>;

export function GetDashboard():Promise<ipc.AgentDashboard>;

export function HideWindow():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartEnrollment():Promise<tray.EnrollmentStartResponse>;
