apiVersion: v1
kind: Secret
metadata:
  name: pdp-secrets
  namespace: trustcloud
type: Opaque
stringData:
  PDP_DATABASE_URL: "postgres://trustcloud:change-me@postgres.database.svc.cluster.local:5432/trustcloud?sslmode=disable"
  PDP_REDIS_URL: "redis://:change-me@redis.redis.svc.cluster.local:6379/0"
  PDP_PKI_TOKEN: "change-me"
  PDP_TRANSIT_KEY: "trustcloud-key"
