apiVersion: v1
kind: Service
metadata:
  name: pdp
  namespace: trustcloud
  labels:
    app.kubernetes.io/name: pdp
    app.kubernetes.io/part-of: trustcloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pdp
  ports:
    - name: https
      port: 8443
      targetPort: https
