apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: trustcloud
type: Opaque
stringData:
  vault-ca.crt: |
    -----BEGIN CERTIFICATE-----
    replace-with-vault-ca-pem
    -----END CERTIFICATE-----
