apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-scim-sync-config
  namespace: trustcloud-idp
  labels:
    app.kubernetes.io/name: keycloak-scim-sync
    app.kubernetes.io/part-of: trustcloud
data:
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "trustcloud-lab"
  KEYCLOAK_AUTH_REALM: "master"
  KEYCLOAK_CLIENT_ID: "admin-cli"
  PDP_BASE_URL: "https://trust-cloud.dev"
  PDP_TLS_SKIP_VERIFY: "false"
  SYNC_INTERVAL: "60s"
  SYNC_ONCE: "false"
  DISABLE_MISSING_USERS: "true"
  DELETE_MISSING_GROUPS: "false"
  SKIP_SERVICE_ACCOUNTS: "true"
  PAGE_SIZE: "100"

