// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDeviceHealth():Promise<main.DeviceHealth>;

export function GetReporter():Promise<main.CloudReporter>;

export function HideWindow():Promise<void>;

export function ShowWindow():Promise<void>;
