// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceHealth() {
  return window['go']['main']['App']['GetDeviceHealth']();
}

export function GetReporter() {
  return window['go']['main']['App']['GetReporter']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
